apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appname }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.localport }}
