output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "region" {
  description = "AWS region"
  value       = var.region
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = local.cluster_name
}

output "postgres_database_host_dev" {
  description = "The database host."
  value = aws_db_instance.rds-dev.address
}

output "postgres_database_host_prod" {
  description = "The database host."
  value = aws_db_instance.rds-prod.address
}

output "postgres_database_name" {
  description = "The database name."
  value = aws_db_instance.rds-dev.name
}

output "postgres_database_port" {
  description = "The database port."
  value = "5432"
}

output "postgres_database_sg_id" {
  description = "The security group ID associated with the database."
  value = aws_security_group.secgrp-rds.id
}